### ISSUE TITLE
Is marshmallow-sqlalchemy needed?

### ISSUE THREAD

**Issue by gleekzorp** [gleekzorp/cory-git-fix-me#7]
It seems we have `marshmallow-sqlalchemy` inside our `pipfile` but we never use it within our `app.py`.

Is this package needed?  While I was building out this practice example I was able to build and deploy without this package.  We might want to to some research to see if we really need it.  Maybe I was getting an error and didn't even notice it.

**Comment by cbass2404** [comment]
When starting the development server it gave me the message saying it was required for the flask portion. Although I never actually called it, the message did go away. It did function without the added files though.

**Comment by gleekzorp** [comment]
I just pulled up the logs for my `heroku` deployment of this.  I do get a warning so we will want to keep this package.

`UserWarning: Flask-SQLAlchemy integration requires marshmallow-sqlalchemy to be installed.`

This warning comes up during the time of when the `flask_marshmallow` portion is being imported.
